name: sachithsPipeline
  
on:
  push:
    branches: ["main"]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Check repo
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t sachiya01/app .

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push image 
        run: docker push sachiya01/app

        ##