name: CICD

on:
  push: 
    branches: ["Sachith"]

jobs:
  stage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: actions/checkout@v3

      - name: Build container
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/myapp:latest

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push image to docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/myapp:latest
##